Fix "Duplicate scenario name" in Ansible Molecule Workflow
(Migrate Ansible Molecule back from podman to docker)

(The Github Ansible Molecule Workflow does not work with podman.)

The workflow reports this error:

  WARNING  Driver podman does not provide a schema.
  WARNING  Driver podman does not provide a schema.
  WARNING  Driver podman does not provide a schema.
  WARNING  Driver podman does not provide a schema.
  WARNING  Driver podman does not provide a schema.
  CRITICAL Duplicate scenario name 'default' found.  Exiting.
  Error: The operation was canceled.

It seems that the latest Ansible Molecule version doesn't like it
anymore when we symlink to the "default" molecule.yml.

There is a `--base-config` options since quite a while:
https://github.com/ansible/molecule/commit/b23402500ddeab0601c1e207a1acf73666adec02

Unfortunately every scenario needs a molecule.yml. Needed to touch one
for each scenario.

The default base config is .config/molecule/config.yml.

In case we need it, added a docker configuration from https://github.com/geerlingguy/ansible-role-ntp/blob/master/molecule/default/molecule.yml